language: ruby
rvm:
- 2.3.0
bundler_args: --jobs=2
script:
script:
  - bundle exec rake db:setup
  - bundle exec rake spec
  - git clone --depth=50 https://github.com/mozilla/geckodriver.git mozilla/geckodriver
cache: bundler
services:
  - postgresql
addons:
  postgresql: "9.4"
  firefox: "50.0"

